package com.example.test;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WeWriteEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .WeWriteEvent.EventType type = 1;
    /**
     * <code>required .WeWriteEvent.EventType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .WeWriteEvent.EventType type = 1;</code>
     */
    Event.WeWriteEvent.EventType getType();

    // optional string newText = 2;
    /**
     * <code>optional string newText = 2;</code>
     */
    boolean hasNewText();
    /**
     * <code>optional string newText = 2;</code>
     */
    java.lang.String getNewText();
    /**
     * <code>optional string newText = 2;</code>
     */
    com.google.protobuf.ByteString
        getNewTextBytes();

    // optional int32 textStart = 3;
    /**
     * <code>optional int32 textStart = 3;</code>
     */
    boolean hasTextStart();
    /**
     * <code>optional int32 textStart = 3;</code>
     */
    int getTextStart();

    // optional int32 replacedTextLength = 4;
    /**
     * <code>optional int32 replacedTextLength = 4;</code>
     */
    boolean hasReplacedTextLength();
    /**
     * <code>optional int32 replacedTextLength = 4;</code>
     */
    int getReplacedTextLength();

    // optional int32 cursorStart = 5;
    /**
     * <code>optional int32 cursorStart = 5;</code>
     */
    boolean hasCursorStart();
    /**
     * <code>optional int32 cursorStart = 5;</code>
     */
    int getCursorStart();

    // optional int64 participantID = 6;
    /**
     * <code>optional int64 participantID = 6;</code>
     */
    boolean hasParticipantID();
    /**
     * <code>optional int64 participantID = 6;</code>
     */
    long getParticipantID();
  }
  /**
   * Protobuf type {@code WeWriteEvent}
   */
  public static final class WeWriteEvent extends
      com.google.protobuf.GeneratedMessage
      implements WeWriteEventOrBuilder {
    // Use WeWriteEvent.newBuilder() to construct.
    private WeWriteEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WeWriteEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WeWriteEvent defaultInstance;
    public static WeWriteEvent getDefaultInstance() {
      return defaultInstance;
    }

    public WeWriteEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WeWriteEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Event.WeWriteEvent.EventType value = Event.WeWriteEvent.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              newText_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              textStart_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              replacedTextLength_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              cursorStart_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              participantID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Event.internal_static_WeWriteEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Event.internal_static_WeWriteEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Event.WeWriteEvent.class, Event.WeWriteEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<WeWriteEvent> PARSER =
        new com.google.protobuf.AbstractParser<WeWriteEvent>() {
      public WeWriteEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeWriteEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WeWriteEvent> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code WeWriteEvent.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOVECURSOR = 0;</code>
       */
      MOVECURSOR(0, 0),
      /**
       * <code>CHANGETEXT = 1;</code>
       */
      CHANGETEXT(1, 1),
      ;

      /**
       * <code>MOVECURSOR = 0;</code>
       */
      public static final int MOVECURSOR_VALUE = 0;
      /**
       * <code>CHANGETEXT = 1;</code>
       */
      public static final int CHANGETEXT_VALUE = 1;


      public final int getNumber() { return value; }

      public static EventType valueOf(int value) {
        switch (value) {
          case 0: return MOVECURSOR;
          case 1: return CHANGETEXT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Event.WeWriteEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:WeWriteEvent.EventType)
    }

    private int bitField0_;
    // required .WeWriteEvent.EventType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private Event.WeWriteEvent.EventType type_;
    /**
     * <code>required .WeWriteEvent.EventType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .WeWriteEvent.EventType type = 1;</code>
     */
    public Event.WeWriteEvent.EventType getType() {
      return type_;
    }

    // optional string newText = 2;
    public static final int NEWTEXT_FIELD_NUMBER = 2;
    private java.lang.Object newText_;
    /**
     * <code>optional string newText = 2;</code>
     */
    public boolean hasNewText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string newText = 2;</code>
     */
    public java.lang.String getNewText() {
      java.lang.Object ref = newText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string newText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewTextBytes() {
      java.lang.Object ref = newText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 textStart = 3;
    public static final int TEXTSTART_FIELD_NUMBER = 3;
    private int textStart_;
    /**
     * <code>optional int32 textStart = 3;</code>
     */
    public boolean hasTextStart() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 textStart = 3;</code>
     */
    public int getTextStart() {
      return textStart_;
    }

    // optional int32 replacedTextLength = 4;
    public static final int REPLACEDTEXTLENGTH_FIELD_NUMBER = 4;
    private int replacedTextLength_;
    /**
     * <code>optional int32 replacedTextLength = 4;</code>
     */
    public boolean hasReplacedTextLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 replacedTextLength = 4;</code>
     */
    public int getReplacedTextLength() {
      return replacedTextLength_;
    }

    // optional int32 cursorStart = 5;
    public static final int CURSORSTART_FIELD_NUMBER = 5;
    private int cursorStart_;
    /**
     * <code>optional int32 cursorStart = 5;</code>
     */
    public boolean hasCursorStart() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 cursorStart = 5;</code>
     */
    public int getCursorStart() {
      return cursorStart_;
    }

    // optional int64 participantID = 6;
    public static final int PARTICIPANTID_FIELD_NUMBER = 6;
    private long participantID_;
    /**
     * <code>optional int64 participantID = 6;</code>
     */
    public boolean hasParticipantID() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 participantID = 6;</code>
     */
    public long getParticipantID() {
      return participantID_;
    }

    private void initFields() {
      type_ = Event.WeWriteEvent.EventType.MOVECURSOR;
      newText_ = "";
      textStart_ = 0;
      replacedTextLength_ = 0;
      cursorStart_ = 0;
      participantID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNewTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, textStart_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, replacedTextLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, cursorStart_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, participantID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNewTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, textStart_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, replacedTextLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cursorStart_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, participantID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Event.WeWriteEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Event.WeWriteEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Event.WeWriteEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Event.WeWriteEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Event.WeWriteEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Event.WeWriteEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Event.WeWriteEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Event.WeWriteEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Event.WeWriteEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Event.WeWriteEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Event.WeWriteEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WeWriteEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Event.WeWriteEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Event.internal_static_WeWriteEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Event.internal_static_WeWriteEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Event.WeWriteEvent.class, Event.WeWriteEvent.Builder.class);
      }

      // Construct using Event.WeWriteEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = Event.WeWriteEvent.EventType.MOVECURSOR;
        bitField0_ = (bitField0_ & ~0x00000001);
        newText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        textStart_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        replacedTextLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        cursorStart_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        participantID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Event.internal_static_WeWriteEvent_descriptor;
      }

      public Event.WeWriteEvent getDefaultInstanceForType() {
        return Event.WeWriteEvent.getDefaultInstance();
      }

      public Event.WeWriteEvent build() {
        Event.WeWriteEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Event.WeWriteEvent buildPartial() {
        Event.WeWriteEvent result = new Event.WeWriteEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newText_ = newText_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.textStart_ = textStart_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.replacedTextLength_ = replacedTextLength_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cursorStart_ = cursorStart_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.participantID_ = participantID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Event.WeWriteEvent) {
          return mergeFrom((Event.WeWriteEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Event.WeWriteEvent other) {
        if (other == Event.WeWriteEvent.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasNewText()) {
          bitField0_ |= 0x00000002;
          newText_ = other.newText_;
          onChanged();
        }
        if (other.hasTextStart()) {
          setTextStart(other.getTextStart());
        }
        if (other.hasReplacedTextLength()) {
          setReplacedTextLength(other.getReplacedTextLength());
        }
        if (other.hasCursorStart()) {
          setCursorStart(other.getCursorStart());
        }
        if (other.hasParticipantID()) {
          setParticipantID(other.getParticipantID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Event.WeWriteEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Event.WeWriteEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .WeWriteEvent.EventType type = 1;
      private Event.WeWriteEvent.EventType type_ = Event.WeWriteEvent.EventType.MOVECURSOR;
      /**
       * <code>required .WeWriteEvent.EventType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .WeWriteEvent.EventType type = 1;</code>
       */
      public Event.WeWriteEvent.EventType getType() {
        return type_;
      }
      /**
       * <code>required .WeWriteEvent.EventType type = 1;</code>
       */
      public Builder setType(Event.WeWriteEvent.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .WeWriteEvent.EventType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = Event.WeWriteEvent.EventType.MOVECURSOR;
        onChanged();
        return this;
      }

      // optional string newText = 2;
      private java.lang.Object newText_ = "";
      /**
       * <code>optional string newText = 2;</code>
       */
      public boolean hasNewText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string newText = 2;</code>
       */
      public java.lang.String getNewText() {
        java.lang.Object ref = newText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          newText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string newText = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNewTextBytes() {
        java.lang.Object ref = newText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string newText = 2;</code>
       */
      public Builder setNewText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        newText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string newText = 2;</code>
       */
      public Builder clearNewText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newText_ = getDefaultInstance().getNewText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string newText = 2;</code>
       */
      public Builder setNewTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        newText_ = value;
        onChanged();
        return this;
      }

      // optional int32 textStart = 3;
      private int textStart_ ;
      /**
       * <code>optional int32 textStart = 3;</code>
       */
      public boolean hasTextStart() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 textStart = 3;</code>
       */
      public int getTextStart() {
        return textStart_;
      }
      /**
       * <code>optional int32 textStart = 3;</code>
       */
      public Builder setTextStart(int value) {
        bitField0_ |= 0x00000004;
        textStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 textStart = 3;</code>
       */
      public Builder clearTextStart() {
        bitField0_ = (bitField0_ & ~0x00000004);
        textStart_ = 0;
        onChanged();
        return this;
      }

      // optional int32 replacedTextLength = 4;
      private int replacedTextLength_ ;
      /**
       * <code>optional int32 replacedTextLength = 4;</code>
       */
      public boolean hasReplacedTextLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 replacedTextLength = 4;</code>
       */
      public int getReplacedTextLength() {
        return replacedTextLength_;
      }
      /**
       * <code>optional int32 replacedTextLength = 4;</code>
       */
      public Builder setReplacedTextLength(int value) {
        bitField0_ |= 0x00000008;
        replacedTextLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 replacedTextLength = 4;</code>
       */
      public Builder clearReplacedTextLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        replacedTextLength_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cursorStart = 5;
      private int cursorStart_ ;
      /**
       * <code>optional int32 cursorStart = 5;</code>
       */
      public boolean hasCursorStart() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 cursorStart = 5;</code>
       */
      public int getCursorStart() {
        return cursorStart_;
      }
      /**
       * <code>optional int32 cursorStart = 5;</code>
       */
      public Builder setCursorStart(int value) {
        bitField0_ |= 0x00000010;
        cursorStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorStart = 5;</code>
       */
      public Builder clearCursorStart() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cursorStart_ = 0;
        onChanged();
        return this;
      }

      // optional int64 participantID = 6;
      private long participantID_ ;
      /**
       * <code>optional int64 participantID = 6;</code>
       */
      public boolean hasParticipantID() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 participantID = 6;</code>
       */
      public long getParticipantID() {
        return participantID_;
      }
      /**
       * <code>optional int64 participantID = 6;</code>
       */
      public Builder setParticipantID(long value) {
        bitField0_ |= 0x00000020;
        participantID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 participantID = 6;</code>
       */
      public Builder clearParticipantID() {
        bitField0_ = (bitField0_ & ~0x00000020);
        participantID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WeWriteEvent)
    }

    static {
      defaultInstance = new WeWriteEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WeWriteEvent)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WeWriteEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WeWriteEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\"\316\001\n\014WeWriteEvent\022%\n\004type\030\001" +
      " \002(\0162\027.WeWriteEvent.EventType\022\017\n\007newText" +
      "\030\002 \001(\t\022\021\n\ttextStart\030\003 \001(\005\022\032\n\022replacedTex" +
      "tLength\030\004 \001(\005\022\023\n\013cursorStart\030\005 \001(\005\022\025\n\rpa" +
      "rticipantID\030\006 \001(\003\"+\n\tEventType\022\016\n\nMOVECU" +
      "RSOR\020\000\022\016\n\nCHANGETEXT\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WeWriteEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WeWriteEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WeWriteEvent_descriptor,
              new java.lang.String[] { "Type", "NewText", "TextStart", "ReplacedTextLength", "CursorStart", "ParticipantID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
