package com.example.test;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TextChange.proto

public final class TextChange {
  private TextChange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyTextChangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string newText = 1;
    /**
     * <code>required string newText = 1;</code>
     */
    boolean hasNewText();
    /**
     * <code>required string newText = 1;</code>
     */
    java.lang.String getNewText();
    /**
     * <code>required string newText = 1;</code>
     */
    com.google.protobuf.ByteString
        getNewTextBytes();

    // required int32 start = 2;
    /**
     * <code>required int32 start = 2;</code>
     */
    boolean hasStart();
    /**
     * <code>required int32 start = 2;</code>
     */
    int getStart();

    // required int32 replacedTextLength = 3;
    /**
     * <code>required int32 replacedTextLength = 3;</code>
     */
    boolean hasReplacedTextLength();
    /**
     * <code>required int32 replacedTextLength = 3;</code>
     */
    int getReplacedTextLength();

    // required int32 newTextLength = 4;
    /**
     * <code>required int32 newTextLength = 4;</code>
     */
    boolean hasNewTextLength();
    /**
     * <code>required int32 newTextLength = 4;</code>
     */
    int getNewTextLength();
  }
  /**
   * Protobuf type {@code MyTextChange}
   */
  public static final class MyTextChange extends
      com.google.protobuf.GeneratedMessage
      implements MyTextChangeOrBuilder {
    // Use MyTextChange.newBuilder() to construct.
    private MyTextChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyTextChange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyTextChange defaultInstance;
    public static MyTextChange getDefaultInstance() {
      return defaultInstance;
    }

    public MyTextChange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyTextChange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              newText_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              start_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              replacedTextLength_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              newTextLength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TextChange.internal_static_MyTextChange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TextChange.internal_static_MyTextChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TextChange.MyTextChange.class, TextChange.MyTextChange.Builder.class);
    }

    public static com.google.protobuf.Parser<MyTextChange> PARSER =
        new com.google.protobuf.AbstractParser<MyTextChange>() {
      public MyTextChange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyTextChange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyTextChange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string newText = 1;
    public static final int NEWTEXT_FIELD_NUMBER = 1;
    private java.lang.Object newText_;
    /**
     * <code>required string newText = 1;</code>
     */
    public boolean hasNewText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string newText = 1;</code>
     */
    public java.lang.String getNewText() {
      java.lang.Object ref = newText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string newText = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNewTextBytes() {
      java.lang.Object ref = newText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 start = 2;
    public static final int START_FIELD_NUMBER = 2;
    private int start_;
    /**
     * <code>required int32 start = 2;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 start = 2;</code>
     */
    public int getStart() {
      return start_;
    }

    // required int32 replacedTextLength = 3;
    public static final int REPLACEDTEXTLENGTH_FIELD_NUMBER = 3;
    private int replacedTextLength_;
    /**
     * <code>required int32 replacedTextLength = 3;</code>
     */
    public boolean hasReplacedTextLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 replacedTextLength = 3;</code>
     */
    public int getReplacedTextLength() {
      return replacedTextLength_;
    }

    // required int32 newTextLength = 4;
    public static final int NEWTEXTLENGTH_FIELD_NUMBER = 4;
    private int newTextLength_;
    /**
     * <code>required int32 newTextLength = 4;</code>
     */
    public boolean hasNewTextLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 newTextLength = 4;</code>
     */
    public int getNewTextLength() {
      return newTextLength_;
    }

    private void initFields() {
      newText_ = "";
      start_ = 0;
      replacedTextLength_ = 0;
      newTextLength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNewText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReplacedTextLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewTextLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNewTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, start_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, replacedTextLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, newTextLength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNewTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, start_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, replacedTextLength_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, newTextLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static TextChange.MyTextChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextChange.MyTextChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextChange.MyTextChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TextChange.MyTextChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TextChange.MyTextChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TextChange.MyTextChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static TextChange.MyTextChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static TextChange.MyTextChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static TextChange.MyTextChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static TextChange.MyTextChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(TextChange.MyTextChange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyTextChange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements TextChange.MyTextChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TextChange.internal_static_MyTextChange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TextChange.internal_static_MyTextChange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TextChange.MyTextChange.class, TextChange.MyTextChange.Builder.class);
      }

      // Construct using TextChange.MyTextChange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        newText_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        replacedTextLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        newTextLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TextChange.internal_static_MyTextChange_descriptor;
      }

      public TextChange.MyTextChange getDefaultInstanceForType() {
        return TextChange.MyTextChange.getDefaultInstance();
      }

      public TextChange.MyTextChange build() {
        TextChange.MyTextChange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TextChange.MyTextChange buildPartial() {
        TextChange.MyTextChange result = new TextChange.MyTextChange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newText_ = newText_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.replacedTextLength_ = replacedTextLength_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newTextLength_ = newTextLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TextChange.MyTextChange) {
          return mergeFrom((TextChange.MyTextChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TextChange.MyTextChange other) {
        if (other == TextChange.MyTextChange.getDefaultInstance()) return this;
        if (other.hasNewText()) {
          bitField0_ |= 0x00000001;
          newText_ = other.newText_;
          onChanged();
        }
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasReplacedTextLength()) {
          setReplacedTextLength(other.getReplacedTextLength());
        }
        if (other.hasNewTextLength()) {
          setNewTextLength(other.getNewTextLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNewText()) {
          
          return false;
        }
        if (!hasStart()) {
          
          return false;
        }
        if (!hasReplacedTextLength()) {
          
          return false;
        }
        if (!hasNewTextLength()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TextChange.MyTextChange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TextChange.MyTextChange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string newText = 1;
      private java.lang.Object newText_ = "";
      /**
       * <code>required string newText = 1;</code>
       */
      public boolean hasNewText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string newText = 1;</code>
       */
      public java.lang.String getNewText() {
        java.lang.Object ref = newText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          newText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string newText = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNewTextBytes() {
        java.lang.Object ref = newText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string newText = 1;</code>
       */
      public Builder setNewText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string newText = 1;</code>
       */
      public Builder clearNewText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newText_ = getDefaultInstance().getNewText();
        onChanged();
        return this;
      }
      /**
       * <code>required string newText = 1;</code>
       */
      public Builder setNewTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newText_ = value;
        onChanged();
        return this;
      }

      // required int32 start = 2;
      private int start_ ;
      /**
       * <code>required int32 start = 2;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 start = 2;</code>
       */
      public int getStart() {
        return start_;
      }
      /**
       * <code>required int32 start = 2;</code>
       */
      public Builder setStart(int value) {
        bitField0_ |= 0x00000002;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 start = 2;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000002);
        start_ = 0;
        onChanged();
        return this;
      }

      // required int32 replacedTextLength = 3;
      private int replacedTextLength_ ;
      /**
       * <code>required int32 replacedTextLength = 3;</code>
       */
      public boolean hasReplacedTextLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 replacedTextLength = 3;</code>
       */
      public int getReplacedTextLength() {
        return replacedTextLength_;
      }
      /**
       * <code>required int32 replacedTextLength = 3;</code>
       */
      public Builder setReplacedTextLength(int value) {
        bitField0_ |= 0x00000004;
        replacedTextLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 replacedTextLength = 3;</code>
       */
      public Builder clearReplacedTextLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        replacedTextLength_ = 0;
        onChanged();
        return this;
      }

      // required int32 newTextLength = 4;
      private int newTextLength_ ;
      /**
       * <code>required int32 newTextLength = 4;</code>
       */
      public boolean hasNewTextLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 newTextLength = 4;</code>
       */
      public int getNewTextLength() {
        return newTextLength_;
      }
      /**
       * <code>required int32 newTextLength = 4;</code>
       */
      public Builder setNewTextLength(int value) {
        bitField0_ |= 0x00000008;
        newTextLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 newTextLength = 4;</code>
       */
      public Builder clearNewTextLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newTextLength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyTextChange)
    }

    static {
      defaultInstance = new MyTextChange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MyTextChange)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTextChange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MyTextChange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TextChange.proto\"a\n\014MyTextChange\022\017\n\007ne" +
      "wText\030\001 \002(\t\022\r\n\005start\030\002 \002(\005\022\032\n\022replacedTe" +
      "xtLength\030\003 \002(\005\022\025\n\rnewTextLength\030\004 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MyTextChange_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MyTextChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MyTextChange_descriptor,
              new java.lang.String[] { "NewText", "Start", "ReplacedTextLength", "NewTextLength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
